labelPRBasedOnFilePath:
  # Add 'label1' to any changes within 'example' folder or any subfolders
  ReadMe:
    - README.md
addReviewerBasedOnLabel:
  defaultReviewers:
    - tyler-mairose-sp
  labels:
    ReadMe:
      - jordan-violet-sp
    documentation:
      - colin-mckibben-sp
